### ISSUE TITLE
relative import

### ISSUE THREAD

**Issue by aaron4444** [CFN-softbio/pycxdgui#2]
(pycxdgui) D:\Software\pycxdgui\pycxdgui>python startGUI.py
Traceback (most recent call last):
  File "startGUI.py", line 1, in <module>
    from PyQt5 import QtGui
ImportError: No module named 'PyQt5'

(pycxdgui) D:\Software\pycxdgui\pycxdgui>python startGUI.py
Traceback (most recent call last):
  File "startGUI.py", line 2, in <module>
    from gui.SAXSMainGUI import SAXSGUI
  File "D:\Software\pycxdgui\pycxdgui\gui\SAXSMainGUI.py", line 5, in <module>
    from ..tools.average import runningaverage
ValueError: attempted relative import beyond top-level package

**Comment by aaron4444** [comment]
Ok, so if i change a bunch of things it works.....take a while to debug. 

i had to mess with TOOLS, MASK, i had to install pyqt5 instead of pyqt4

install scikit-beam thru conda forge
